version: '3'

services:
  organizations:
    build:
      context: .
    command:
      - /usr/local/bin/start_2gis_organizations.sh
    env_file:
      - prod.env

  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: