version: '3'

services:

  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_backup:/backup

  redis:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
  mongo_backup: