version: '3'

services:

  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: